/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Multiplayer.Sudoku;

import org.junit.Test;
import static org.junit.Assert.*;
import Multiplayer.Sudoku.Protocol.*;

public class PacketTest {
    @Test public void testEncodedPacketCanBeDecoded() {
        byte[] input_message = "Example String Message".getBytes();

        
        Packet packet = new Packet(PacketTypes.INVALID);
        packet.setMessage(input_message);
        
        Packet new_packet = new Packet(packet.getEncoded());
        
        assertArrayEquals(input_message, new_packet.getMessage());
    }
}